# Increase the memory available to Gradle.
org.gradle.jvmargs=-Xmx1G
# Fabric Properties
min_minecraft_version=26.2
max_minecraft_version=26.2
loader_version=0.19.3
loom_version=1.17-SNAPSHOT
# Mod Properties
mod_version=0.1.2
maven_group=dev.tori
archives_base_name=happierghasts
# Dependencies
# Fabric API
fabric_api_version=0.159.0+26.2
# https://maven.wispforest.io/io/wispforest/owo-lib/
owo_version=0.13.1+26.2